### PR TITLE
Fix non-Windows terminals assumed to always support 256-color

### PR DESCRIPTION
**Pull request by mislav**
Backports https://github.com/cli/cli/pull/6356

### CODE REVIEW

**Review by vilmibm — APPROVED** [review]

**Review by samcoe — APPROVED** [review]
Code looks good to me. Interesting that govulncheck found an vulnerability that dependabot didn't. The vulnerability wasn't introduced in this PR so it is probably okay to merge, and we can fix the vulnerability in a follow up PR.

**Comment by heaths** [comment]
Wouldn't this completely break alternate screen buffers on *nix then? There are other ways of detecting whether VT sequences are supported:

* Using `tput` e.g., https://unix.stackexchange.com/questions/450365/check-if-terminal-supports-24-bit-true-color
* https://github.com/microsoft/terminal/issues/1040#issuecomment-1043650915

See https://github.com/cli/cli/pull/6356#issuecomment-1276773296 for more information.

**Comment by heaths** [comment]
I submitted https://github.com/cli/cli/pull/6435 to restore behavior without impacting this PR, since the change was only to restore the original behavior without assumptions of VT support this change inferred. This PR would actually be a good fix, but long-term support for various color or other VT support might be good to add to go-gh. See https://github.com/cli/cli/pull/6435#issuecomment-1277776665 for possibilities.

**Comment by mislav** [comment]
@heaths I don't see how this can break alternate screen buffers on *nix. There is still an issue with that in the CLI repo, I agree, but we will resolve that in that repo.

**Comment by heaths** [comment]
Agreed. Please see my latest comment.

**Comment by heaths** [comment]
To clarify my comment about VT support, I was suggesting maybe something in this module could define, but perhaps that would best be in one of @mattn's many term modules, if it isn't already (I couldn't find one).

**Comment by mattn** [comment]
Can I help you? If you can explain how to reproduce the problem, I can fix that.

**Comment by heaths** [comment]
Mainly, with all the terminal modules you have, was wondering if any of them might be a good place to put better VT support detection into. See https://github.com/cli/cli/pull/6435#issuecomment-1277776665 for some thoughts. We've also been wrestling with some of these ideas for Windows Terminal as well. If you think one of your modules might be appropriate, maybe you or I could open an issue and discuss more there.

**Pull request merged**
